name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Trigger when a push is made to the main branch

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the Google Cloud SDK and authenticate using the service account key
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Configure Docker to authenticate with Google Container Registry
      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      # Build the Docker image with a unique tag based on the commit SHA
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/midi-generation:${{ github.sha }} .

      # Push the Docker image to Container Registry
      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/midi-generation:${{ github.sha }}

      # Deploy the pushed image to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy midi-generation \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/midi-generation:${{ github.sha }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
